title: Keep learning to code!
author: GitHub Lanasp
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Keep learning to code!
theme: jekyll-theme-architect


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


